### ISSUE TITLE
Char type used for variables in the negative range causes preliminary tests to fail.

### ISSUE THREAD

**Issue by kiik** [ronan-kerviche/glip-lib#1]
Seemingly valid pipeline scripts fail to compile.

For example the line:

`CALL:FORMAT_TO_CONSTANT(outputFormat)`

results to an 'no body defined' error.

This seems to happen because 'bodyPresent' variable in 'LayoutLoaderModule' class has type char, while -1 is defined as its value in 'FORMAT_TO_CONSTANT' module. This results in underflow, causing its value to become 255 by the time 'preliminaryTests' method body is reached which in turn makes a mess of the test condition results.

I've attached a patch of the changes I had to do for everything to start working for me.

[patch_040217-2131.tar.gz](https://github.com/ronan-kerviche/glip-lib/files/752506/patch_040217-2131.tar.gz)

**Comment by ronan-kerviche** [comment]
Good catch! I had never seen that one before. Which compiler are you using?

**Comment by kiik** [comment]
I'm compiling with gcc 5.4.0 on ARM Cortex-A57.
It seems kinda weird to me as well, because is working for me on different x86_64 Intel CPU's. Perhaps when compiling for the Intel CPU these underflow cases are somehow handled by the compiler, or the underlying memory still behaves like a larger integer even when char type is used.

**Comment by ronan-kerviche** [comment]
Yes, for ARM it seems that the compilers will default to an unsigned char. I have mostly worked on X86 where it is usually the opposite... bad habit I guess...
I updated the code with [02d1c63](https://github.com/ronan-kerviche/glip-lib/commit/02d1c634cb941a83c06e5745e389aa2fa44598c7) and [c482ceb](https://github.com/ronan-kerviche/glip-lib/commit/c482cebc7b9b8b71161769067f49f6251e82339a).
